// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1gyQ9gLtbch3fTZxQWWf0anx-L6xYrdQ',
    appId: '1:603874645179:web:392ff8bbf59c9c88ecc59e',
    messagingSenderId: '603874645179',
    projectId: 'caloryauth',
    authDomain: 'caloryauth.firebaseapp.com',
    storageBucket: 'caloryauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuYo5o3gDKNkUa4wSxhACAGoo1kmsF9U',
    appId: '1:603874645179:android:6a8e348a2736b932ecc59e',
    messagingSenderId: '603874645179',
    projectId: 'caloryauth',
    storageBucket: 'caloryauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB13hGp7GgaRk1oEZMj74pDaJjoy9iHm2M',
    appId: '1:603874645179:ios:af17f97095d267e5ecc59e',
    messagingSenderId: '603874645179',
    projectId: 'caloryauth',
    storageBucket: 'caloryauth.firebasestorage.app',
    iosBundleId: 'com.example.recompAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB13hGp7GgaRk1oEZMj74pDaJjoy9iHm2M',
    appId: '1:603874645179:ios:af17f97095d267e5ecc59e',
    messagingSenderId: '603874645179',
    projectId: 'caloryauth',
    storageBucket: 'caloryauth.firebasestorage.app',
    iosBundleId: 'com.example.recompAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1gyQ9gLtbch3fTZxQWWf0anx-L6xYrdQ',
    appId: '1:603874645179:web:b08db66815c4d3b1ecc59e',
    messagingSenderId: '603874645179',
    projectId: 'caloryauth',
    authDomain: 'caloryauth.firebaseapp.com',
    storageBucket: 'caloryauth.firebasestorage.app',
  );
}
